# Generated by Django 2.2.7 on 2019-11-21 11:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para esta canción', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ingrese el nombre de la canción', max_length=200)),
                ('author', models.CharField(help_text='Ingrese el nombre del autor', max_length=200)),
            ],
        ),
    ]
